routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\postController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\FavoriteController;
use App\Http\Controllers\CommentController;
use \App\Http\Controllers\LikeController;
use \App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PostController::class, 'index'])->name('home');

Route::resource('posts', PostController::class);

Route::middleware('auth')->group( function() {
    Route::get('your-favorites',            [FavoriteController::class, 'show']);

    Route::get('/like/{id}/add',            [LikeController::class, 'add']);
    Route::get('/like/{id}/delete',         [LikeController::class, 'delete']);

    Route::get('/add-favourite/{slug}',     [FavoriteController::class, 'add']);
    Route::get('/delete-favourite/{slug}',  [FavoriteController::class, 'delete']);

    Route::post('/comments/{slug}',         [CommentController::class, 'add']);
    Route::post('/comments/{slug}/edit',    [CommentController::class, 'update']);
    Route::delete('/comments/{id}',         [CommentController::class, 'delete']);

    Route::get('/edit-profile',         [RegistrationController::class, 'edit']);
    Route::post('/edit-profile',        [RegistrationController::class, 'update']);

    Route::get('/change-password',      [RegistrationController::class, 'editPassword']);
    Route::post('/change-password',     [RegistrationController::class, 'updatePassword']);

    Route::get('/set-admin',            [AdminController::class, 'set']);

    Route::get('/logout',  [SessionController::class, 'destroy'])->name('logout');
});

Route::middleware('guest')->group( function() {
    Route::get('/register',             [RegistrationController::class, 'create']);
    Route::post('/upload',              [RegistrationController::class, 'upload'])->name('reg');
    Route::post('/store-user',    [RegistrationController::class, 'storeUser'])->name('saveUser');

    Route::get('/login',                [SessionController::class, 'create'])->name('login');
    Route::post('login',                [SessionController::class, 'store']);

    Route::prefix('google')->name('google.')->group( function(){
        Route::get('login',             [GoogleController::class, 'loginWithGoogle'])->name('login');
        Route::any('callback',          [GoogleController::class, 'callbackFromGoogle'])->name('callback');
    });

    Route::get('/change',      [GoogleController::class, 'change'])->name('change');

});

Route::get('/logout',  [SessionController::class, 'destroy'])->name('logout');

Route::post('/change', [GoogleController::class, 'updateAndCreate']);

Route::prefix('admin')->middleware('admin')->group(function () {
    Route::get ('/',                    [AdminController::class, 'index']);
    Route::get('/{slug}',               [AdminController::class, 'show']);
    Route::get ('/users/{id}/edit',     [AdminController::class, 'editUser']);
    Route::get ('/posts/{id}/edit',     [AdminController::class, 'editPost']);

    Route::get ('/users/{id}/block',    [AdminController::class, 'block']);
    Route::get('/users/{id}/unblock',   [AdminController::class, 'unblock']);
});


//Route::get('/test', function() {
//   return View('posts.test');
//});

resources/views/admin/comments.blade.php
<x-admin.layout>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Comments Management</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Commented by</th>
                            <th>Content</th>
                            <th>On post</th>
                            <th>Reply to</th>
                            <th>Created date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($comments as $comment)
                        <tr>
                            <td><a href="/posts/{{ $comment->post->slug }}#comment-{{ $comment->id }}" target="_blank">{{ $comment->id }}</a></td>
                            <td>{{ $comment->user->name }}</td>
                            <td>{{ $comment->content }}</td>
                            <td>{{ $comment->post->title }}</td>
                            <td>{{ ($comment->parent_id === null) ? '' : $comment->replied->content }}</td>
                            <td>{{ $comment->created_at }}</td>
                            <td>
                                <button type="submit" class="btn btn-danger" onclick="deleteConfirm({{ $comment->id }})" form="deleteForm" data-toggle="tooltip" title='Delete'>Delete</button>

                                <form method="post" action="/comments/{{ $comment->id }}" id="dComment-{{ $comment->id }}">
                                    @csrf
                                    <input name="_method" type="hidden" value="DELETE">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

            <script type="text/javascript">
                function deleteConfirm(id){
                    var form = document.getElementById('dComment-' + id)

                    swal({
                        title: "Are you sure you want to delete this comment?",
                        text: "If you delete this, it will be gone forever.",
                        icon: "warning",
                        buttons: true,
                    }).then(isConfirmed => {
                        if(isConfirmed) {
                            form.submit();
                        }
                    });
                };

                // $('.delete_confirm').click(function(event) {
                //     var form =  $(this).closest("form");
                //     var name = $(this).data("name");
                //     event.preventDefault();
                //
                //     swal({
                //         title: `Are you sure you want to delete this comment?`,
                //         text: "If you delete this, it will be gone forever.",
                //         icon: "warning",
                //         buttons: true,
                //         dangerMode: true,
                //     })
                //         .then((willDelete) => {
                //             if (willDelete) {
                //                 form.submit();
                //             }
                //         });
                // });
            </script>
</x-admin.layout>

resources/views/admin/index.blade.php
<x-admin.layout>
    <div class="row">
        <x-admin.dashboard-card class="fa-calendar" text="success">
            Today new Posts
            <x-slot name="content">{{ $count['posts'] }}</x-slot>
        </x-admin.dashboard-card>

        <!-- Earnings (Monthly) Card Example -->
        <x-admin.dashboard-card class="fa-comment" text="primary">
            Today new Users
            <x-slot name="content">{{ $count['users'] }}</x-slot>
        </x-admin.dashboard-card>
    </div>

    <div class="row">
        <!-- Area Chart -->
        <div class="col-xl-9 col-lg-7">
            <x-admin.statistic>
                <x-slot name="title">Recently Comments</x-slot>
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Commented By</th>
                            <th>Content</th>
                            <th>On the Post</th>
                            <th>Reply to</th>
                            <th>Comment Date</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($comments as $comment)
                            <tr>
                                <td><a href="/posts/{{ $comment->post->slug }}#comment-{{ $comment->id }}">{{ $comment->id }}</a></td>
                                <td>{{ $comment->user->name }}</td>
                                <td>{{ $comment->content }}</td>
                                <td>{{ $comment->post->title }}</td>
                                <td>{{ ($comment->parent_id === null) ? '' : $comment->replied->content }}</td>
                                <td>{{ $comment->created_at }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </x-admin.statistic>
        </div>

        <!-- Pie Chart -->
        <div class="col-xl-3 col-lg-5">
            <x-admin.statistic>
                <x-slot name="title">Post of the Day</x-slot>
                @if($potd !== null)
                    <a href="posts/{{ $potd->slug }}">{{ $potd->title }}</a>
                    <p class="centered">With</p>
                    {{ count($potd->comments) }} comment(s)
                @else
                    <p>None activity has occurred today</p>
                @endif
            </x-admin.statistic>
        </div>
    </div>
</x-admin.layout>

resources/views/admin/post-edit.blade.php
<x-admin.layout>
    <main class="mb-4">
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-8">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Edit User</h1>
                        </div>
                        <form class="user" method="post" action="{{ route('posts.update', $post->slug) }}" enctype='multipart/form-data'>
                            @csrf

                            <input type="hidden" name="id" value="{{ $post->id }}">

                            <div class="form-group">
                                <label for="title" name="title">Title</label>
                                <input type="text" name="title" id="title" class="form-control form-control-user" value="{{ $post->title }}"
                                       placeholder="Title">

                                @if ($errors->has('title'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="subtitle" name="subtitle">Subtitle</label>
                                <input type="text" name="subtitle" id="subtitle" class="form-control form-control-user" value="{{ $post->subtitle }}"
                                       placeholder="Subtitle">

                                @if ($errors->has('subtitle'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('subtitle') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="content" name="content">Content</label>
                                <textarea name="content" id="editor" class="form-control"
                                          placeholder="Content">{{ $post->content }}</textarea>

                                @if ($errors->has('content'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('content') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="image" name="image">Upload new Background Image</label>
                                <input type="file" name="image" id="image" class="form-control"
                                       placeholder="Subtitle">

                                @if ($errors->has('image'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Edit post" class="btn btn-primary btn-user btn-block">
                            </div>
                        </form>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </main>
    <script>
        ClassicEditor
            .create( document.querySelector( '#editor' ), {
            } )
            .then( editor => {
                window.editor = editor;
            } )
            .catch( err => {
                console.error( err.stack );
            } );
    </script>
</x-admin.layout>

resources/views/admin/posts.blade.php
<x-admin.layout>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Posts Management</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Created date</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td><a href="/posts/{{ $post->slug }}" target="_blank">{{ $post->id }}</a></td>
                            <td><a href="/posts/{{ $post->slug }}" target="_blank">{{ $post->title }}</a></td>
                            <td>{{ $post->author->name }}</td>
                            <td>{{ $post->created_at }}</td>
                            <td>
                                <a class="btn btn-small btn-info show_confirm" href="/admin/posts/{{ $post->id }}/edit">Edit</a>
                                <button type="submit" class="btn btn-danger float-right" onclick="deleteConfirm({{ $post->id }})" form="deleteForm" data-toggle="tooltip" title='Delete'>Delete</button>

                                <form method="post" action="/posts/{{ $post->id }}" id="dForm-{{ $post->id }}">
                                    @csrf
                                    <input name="_method" type="hidden" value="DELETE">
                                </form>
                            </td>
                        </tr>
                    @endforeach
            </tbody>
        </table>
    </div>

    <script type="text/javascript">
        function deleteConfirm(id){
            var form = document.getElementById('dForm-' + id)

            swal({
                title: "Are you sure you want to delete this comment?",
                text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
            }).then(isConfirmed => {
                if(isConfirmed) {
                    form.submit();
                }
            });
        };
    </script>
</x-admin.layout>

resources/views/admin/user-edit.blade.php
<x-admin.layout>
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-8">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Edit User</h1>
                        </div>
                        <form class="user" method="post" action="/edit-profile" enctype='multipart/form-data'>
                            @csrf

                            <input type="hidden" name="id" value="{{ $user->id }}">
                            <input type="hidden" name="old_avatar" value="{{ $user->avatar }}">

                            <div class="form-group">
                                <label for="name" name="name">Name</label>
                                <input type="text" name="name" id="name" class="form-control form-control-user" value="{{ $user->name }}"
                                    placeholder="User Full Name">

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="email" name="email">Email</label>
                                <input type="email" name="email" id="email" class="form-control form-control-user" value="{{ $user->email }}"
                                       placeholder="User Email">

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="avatar" name="avatar">Avatar</label>
                                <input type="file" name="avatar" id="avatar" class="form-control"
                                       placeholder="Change User Avatar">

                                @if ($errors->has('avatar'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('avatar') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="role" name="role">Role</label>
                                <select name="role">
                                    @if($user->role == 1)
                                        <option value="1">Admin</option>
                                        <option value="2">User</option>
                                    @else
                                        <option value="2">User</option>
                                        <option value="1">Admin</option>
                                    @endif
                                </select>

                                @if ($errors->has('avatar'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('avatar') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Edit user's account" class="btn btn-primary btn-user btn-block">
                            </div>
                        </form>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-admin.layout>

resources/views/admin/users.blade.php
<x-admin.layout>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Users Management</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Created date</th>
                        <th>Role</th>
                        <th>Post Owned</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ $user->id }}</a></td>
                            <td>{{ $user->name }}</a></td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->created_at }}</td>
                            <td>{{ ($user->role == 1) ? 'Admin' : 'User' }}</td>
                            <td>{{ count($user->posts) }}</td>

                            <td>
                                @if($user->role != 1)
                                    <a class="btn btn-small btn-info" href="/admin/users/{{ $user->id }}/edit">Edit</a>

                                    @if($user->blocked_until and now()->lessThan($user->blocked_until))
                                        <button class="btn btn-light float-right btn-info"
                                                onclick="blockCheck({{  $user->id. ', ' . now()->diffInDays($user->blocked_until) }})"
                                                >Unblock</button>
                                    @else
                                        <button class="btn btn-warning float-right btn-info" onclick="blockConfirm({{ $user->id }})" id="bUser-{{ $user->id }}"
                                            >Block</button>
                                    @endif
                                @endif
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

            <script type="text/javascript">
                function blockConfirm(id){
                    event.preventDefault()

                    swal({
                        title: "Are you sure you want to block this user for 7 days?",
                        icon: "warning",
                        buttons: true,
                    }).then(isConfirmed => {
                        if(isConfirmed) {
                            location.href = '/admin/users/' + id + '/block';
                        }
                    });
                };

                function blockCheck(id, date) {
                    event.preventDefault()

                    if(date > 1){
                        var plural = 'days'
                    } else {
                        var plural = 'day'
                    }

                    swal({
                        title: "Would you like to unblock this user?",
                        text: "This user has been suspended for " + date + " " + plural,
                        icon: "warning",
                        buttons: true,
                    }).then(isConfirmed => {
                        if(isConfirmed) {
                            location.href = '/admin/users/' + id + '/unblock';
                        }
                    });
                }
            </script>
</x-admin.layout>